name: Deploy de la pagina
on: 
  push:
    branches:
      - main
jos:
  deploy-page:
    runs-on: ubuntu-latest
    steps:
      - name: Ckeckout
        uses: actions/checkout@v2.3.1

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          banch: gh-pages
          folder: .
